// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delete_chirp_by_id.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteChirpById = `-- name: DeleteChirpById :one

DELETE FROM chirps WHERE id = $1 AND user_id = $2 RETURNING id, created_at, updated_at, body, user_id
`

type DeleteChirpByIdParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteChirpById(ctx context.Context, arg DeleteChirpByIdParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, deleteChirpById, arg.ID, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
