// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_email_password.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateEmailPassword = `-- name: UpdateEmailPassword :one

UPDATE users u
SET email = $2, password=$3, updated_at=$4
FROM refresh_tokens t
WHERE u.id = t.user_id
AND u.id = $1
RETURNING u.id, u.created_at, u.updated_at, u.email, u.password, u.is_chirpy_red, t.token
`

type UpdateEmailPasswordParams struct {
	ID        uuid.UUID
	Email     string
	Password  string
	UpdatedAt time.Time
}

type UpdateEmailPasswordRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Email       string
	Password    string
	IsChirpyRed bool
	Token       string
}

func (q *Queries) UpdateEmailPassword(ctx context.Context, arg UpdateEmailPasswordParams) (UpdateEmailPasswordRow, error) {
	row := q.db.QueryRowContext(ctx, updateEmailPassword,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.UpdatedAt,
	)
	var i UpdateEmailPasswordRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
		&i.IsChirpyRed,
		&i.Token,
	)
	return i, err
}
